var R="jd_r",S="jd_s",F="jd_f";
function g(k){try{if(typeof $persistentStore!="undefined")return $persistentStore.read(k)}catch(e){}return null}
function p(k,v){try{if(typeof $persistentStore!="undefined")return $persistentStore.write(v,k)}catch(e){}return false}
if(typeof $request!="undefined"&&typeof $response!="undefined"){var u=$request.url||"",b=$request.body||"";if(u.indexOf("functionId=getCommentOfficerTrialHome")>-1||b.indexOf("functionId=getCommentOfficerTrialHome")>-1){try{p(R,JSON.stringify({url:u,method:"POST",headers:$request.headers,body:b}));p(F,"0");$notify("JD Trial","OK","saved");var o=JSON.parse($response.body);if(o&&process(o.result))}catch(e){}$done({});return}}
function process(r){var a=r.trialActivities||[],ids=[],map={};for(var i=0;i<a.length;i++)if(a[i].claimableNum>0){var d=a[i].activityId+"_"+a[i].skuId;ids.push(d);map[d]={n:a[i].skuName||"SKU"+a[i].skuId,s:a[i].claimableNum}}if(ids.length==0){p(S,JSON.stringify({i:[],m:{},t:Date.now()}));return}var old=JSON.parse(p(S)||"{\"i\":[],\"m\":{}}\"");var od={};for(var j=0;j<old.i.length;j++)od[old.i[j]]=old.m[old.i[j]];var msgs=[];for(var k=0;k<ids.length;k++){var c=ids[k];if(!od[c])msgs.push("🆕 "+map[c].n+" · "+map[c].s+"件");else if(map[c].s>od[c].s)msgs.push("📈 "+map[c].n+" "+od[c].s+"→"+map[c].s)}if(msgs.length>0&&old.i.length>0)$notify("JD · "+ids.length+"件","",msgs.join("\n"));p(S,JSON.stringify({i:ids,m:map,t:Date.now()}))}
function runCron(){var rs=g(R);if(rs){var req={};try{req=JSON.parse(rs)}catch(e){return $done({})}$task.fetch(req).then(function(res){try{var o=JSON.parse(res.body);if(o&&o.result){p(F,"0");process(o.result)}else{h()}}catch(e){h()}},function(){h()})}else{$notify("JD","先抓包","开App→评价中心→试用")}}
function h(){var c=parseInt(g(F)||"0")+1;p(F,""+c);if(c==1||c%4==1)$notify("JD","签名过期","重进App→评价中心→试用")}
runCron();
$done({});
