#!name=MissAv去广告补丁
#!desc=拦截missav.ai广告请求（myavlive/mayzaent/snaptrckr/tsyndicate/partwithner）
#!author=XXXGITHUB777
[rewrite_local]
# snaptrckr 追踪
^https?:\/\/t\.snaptrckr\.fun\/ url reject
# myavlive 广告组件（Player/Spot/lib/Universal）
^https?:\/\/creative\.myavlive\.com\/ url reject
# mayzaent 弹窗广告
^https?:\/\/go\.mayzaent\.com\/ url reject
# tsyndicate 广告SDK
^https?:\/\/cdn\.tsyndicate\.com\/ url reject
# partwithner 广告图片
^https?:\/\/partwithner\.com\/ url reject
[mitm]
hostname = t.snaptrckr.fun, creative.myavlive.com, go.mayzaent.com, cdn.tsyndicate.com, partwithner.com
